### PR TITLE
Winrm execution timeout

### PR DESCRIPTION
**Pull request by jrob**
Please see mitchellh/vagrant#5506

Adds a configurable value for WinRm and the elevated permission shell ExecutionTimeLimit.

Ex: config.winrm.execution_time_limit = "P1D"

Unit tests are passing, please consider for merge.

### CODE REVIEW

**Comment by jrob** [comment]
I don't have a full environment setup to do vagrant dev right now. I may be able to find time to work on it over the next week.

I believe that the config value that I have added is not being initialized in the unit test. Also, it's not at the same level as the other variables for that function so it may need to be changed.

Any feedback is welcome.

**Comment by jrob** [comment]
Fixed unit test.
Cleaned up commits.

Please consider for merge.

**Comment by jrob** [comment]
Any feedback on this pull request?

**Comment by matthewcodes** [comment]
This looks good to me

**Comment by mitchellh** [comment]
Looks fantastic. Thank you!

**Pull request merged**
