### PR TITLE
Use the new Atlas APIs for downloading boxes

### PR DESCRIPTION
**Pull request by sethvargo**
/cc @mitchellh @pearkes

### CODE REVIEW

**Comment by sethvargo** [comment]
I ran smoke tests and was able to download a box from Atlas with this patch :smile:

**Comment by pearkes** [comment]
Yay!

**Comment by mitchellh** [comment]
This has to be reverted. It breaks public API for alternative box implementations. I'll explain more in the next comment.

**Comment by mitchellh** [comment]
This changes the API for boxes to _require_ the `/api/v1/vagrant` path. This is why I didn't get around to doing this yet because I hadn't thought of a clean way to do it, and even told @pearkes it isn't worth it and we should just maintain the old routes forever.

The public API for box discovery is `#{server_url}/box/name` as JSON content-type. This changes it to `#{server_url}/api/v1/boxes/box/name`, which is Atlas specific. This isn't just a theoretical problem either, there are at least 3 separate production implementations of this "protocol" out in the wild.

**Comment by mitchellh** [comment]
Reverted. Let's talk about another way to do this in corp chat.

**Pull request merged**
