### PR TITLE
should fix https://github.com/mitchellh/vagrant/issues/5933 

### LINKED ISSUE #5933: Unable to mount /vagrant folder in 1.7.3
I am running vagrant 1.7.3 with VirtualBox 5.0 on a Windows 8.1 64-bit host.

The guest os is Ubuntu 15.04 64-bit.

When doing a `vagrant up`, it fails to mount the `/vagrant` folder:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:



Stderr from the command:

stdin: is not a tty
chown: changing ownership of ���/vagrant���: Not a directory
```

Relevant part of my vagrant file:

```ruby
config.vm.define "main" do |main_config|
    main_config.vm.network "private_network", ip: "192.168.50.4"
	
	main_config.vm.network "forwarded_port", guest: 80, host: 80
	main_config.vm.synced_folder "D:/work", "/work", type: "smb", owner: "www-data", mount_options: ['file_mode=0777', 'dir_mode=0777']

	main_config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 4
		v.customize ["modifyvm", :id, "--nictype1", "virtio"]
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end
  end
```

### PR DESCRIPTION
**Pull request by cristovaov**
Fixes #5933

### CODE REVIEW

**Comment by cristovaov** [comment]
I tried to do an acceptance test but it unfortunately failed due to lack knowledge on my end. I'd be happy to learn how if someone of your team has time to guide me through it  --- w/ help from: http://stackoverflow.com/a/18034022 -- I'd be already happy if this helped you in anyway. Cheers.

**Comment by mitchellh** [comment]
Fixed by commenting out UNC path conversion. Thanks for the SO link. We'll use that when we look into this further.

**Comment by justicel** [comment]
@mitchellh I think this was closed a bit prematurely. This does indeed fix the mounting issues and also allows UNC to work correctly. I tested it on my end.

**Comment by qkdreyer** [comment]
Thanks for fixing this issue !

**Comment by austinkeeley** [comment]
This worked for me. Thanks for the fix. Hopefully this can get re-opened and merged to be part of the next release.

**Comment by cristovaov** [comment]
@mitchellh Hi Mitchell, could this be looked at again after the holidays? The combining of a fix you implemented and this one (cf: comment above and [this comment](https://github.com/mitchellh/vagrant/issues/5933#issuecomment-167978276)) seems to be the fix. Best wishes!

**Pull request closed without merging**
