### PR TITLE
FIX: no shutdown exception for debian 8 needed

### PR DESCRIPTION
**Pull request by bitprocessor**
The debian8 exception is not needed & not functioning:
The shutdown -h -H command (on vagrant halt), doesn't work correctly, and just forces vagrant to force-shutdown the VM in the end.

The regular "shutdown -h now" works just fine and enabled vagrant to shutdown the machine gracefully.

### CODE REVIEW

**Comment by bitprocessor** [comment]
Tested on debian/jessie64 box
Works like a charm ;)

**Comment by dominikzogg** [comment]
+1, works fine

**Comment by dominikzogg** [comment]
@bitprocessor it seems this solution is not only a solution, got this bug know: https://github.com/mitchellh/vagrant/issues/6332

**Comment by dominikzogg** [comment]
@bitprocessor removing only the part for `halt` works for shutdown, without breaking the host update

**Comment by bitprocessor** [comment]
https://github.com/apertoso/vagrant/commit/e0dad41b0c04de7a35b4fbf44b23eea1b41d1e4e introduced a new issue, preventing Vagrant from changing the hostname ; thanks @dominikzogg for reporting 

Needed to remove the entire exception for Debian 8 in the Debian guest definition.
Fixed in https://github.com/mitchellh/vagrant/commit/cfd4270cdb36833e5a4d322641c68b7a53cacc58

This pull request fixes all files at once.

**Comment by dominikzogg** [comment]
@mitchellh would be cool if you could merge this

**Comment by thinktainer** [comment]
+1

**Comment by caseywebdev** [comment]
:+1: this *halting problem* is quite inconvenient

**Comment by dominikzogg** [comment]
@mitchellh any news in this?

**Comment by EmmanuelKasper** [comment]
I maintain the debian base boxes on https://atlas.hashicorp.com/debian/ and got hit by this bug.
I verified that the current default Linux Behaviour "shutdown -h now &" works on all version of Debian (oldstable, stable, testing)
So this pull should be safe to merge.

**Comment by dominikzogg** [comment]
@mitchellh would be very cool, if you could merge this and tag 1.7.5, cause this is annoying for every user, using debian8 within a box

**Comment by johndoegt** [comment]
Yes, the #5369 was introduced for Debian 8 Release Candidate.. for me, with Vmware-Fusion, it solve a never halt command.. that's why i use the -h -H options. Sorry if it make some other troubles, but with fusion the bugs seem to be alway present. For me this is a very confusing situation.

**Comment by gpkfr** [comment]
i just tried debian/jessie64 box with virtualbox and vagrant 1.7.4 with modified halt command to "-h now"  it seem to work like expected...But with Vmware-Fusion the vagrant halt command never get out !  but with shutdown -h -H it worked as expected ! Very confusing situation, isn't it ?

**Comment by dominikzogg** [comment]
@johndoegt @gpkfr well in worst case those two provider should be handled different. But not solving this, cause its a problem to change it on vmware can't be a solution, most vagrant user use virtualbox, and the status quo is very annoying.

**Comment by stephenreay** [comment]
@mitchellh Any word on getting this merged?

I don't have VMWare Fusion (I'm using Parallels-Vagrant plugin) but I too have seen Debian Jessie guests causing `vagrant halt` to hang until it "forced" the vm to end.

Everything I've read and then tried here, indicates this has *never* been an issue directly related to being a VM, or the VM provider - SystemD (default on Jessie) and OpenSSH server don't play nice together without `libpam-systemd` installed.

I've manually applied this same change and it works as-expected (once `libpam-systemd` is installed on the guest).

**Comment by gpkfr** [comment]
yes, it’s true…. without libpam-systemd package the Gnu/Linux debian fail to halt when used with vmware (but not with virtualbox)…
the Debian8 diversion must be disabled to permit proper shutdown.

Accept my apologies.

**Comment by bitprocessor** [comment]
@mitchellh Now that everybody agrees, could you please merge this so this works again? Even the the person who originally suggested the diversion for Deb8 ( @gpkfr ) now agrees this wasn't a good idea and broke things for the entire world ;)

**Comment by thinktainer** [comment]
:+1:

**Comment by dominikzogg** [comment]
@mitchellh please merge this and tag a new bugfix release

**Comment by crashev** [comment]
One more vote for merging this, lots of ppl are waiting for this :)

**Comment by Sgoettschkes** [comment]
:+1: from my side as well, this is **really** annoying!

**Comment by dominikzogg** [comment]
it seems all love gets into otto instead oft the main project atm...

**Comment by dominikzogg** [comment]
@sethvargo can you merge this PR and tag a new version?

**Comment by razvanphp** [comment]
+100, annoying every day..

**Comment by Sgoettschkes** [comment]
fyi: You can use `vagrant halt --force` which works but doesn't do a normal shutdown and instead "pulls the plug" on the vm. Not an alternative, but a workaround for now.

**Comment by mitchellh** [comment]
@dominikzogg In fact all the love is going into Vagrant ;) you can see my tweets all the Otto experiences are being upstreamed into Vagrant (linked clones, snapshots, etc.). 

Merging this now! Thanks

**Comment by dominikzogg** [comment]
@mitchellh thank you for your response and merging it

**Comment by bitprocessor** [comment]
Thanks @mitchellh for merging!

**Comment by thinktainer** [comment]
:+1: Thank You!

**Comment by dominikzogg** [comment]
@mitchellh is there a release schedule for 1.7.5?

**Comment by mitchellh** [comment]
Hey @dominikzogg, aiming for the end of the month

**Comment by dominikzogg** [comment]
@mitchellh thank you for the fast response

**Comment by dominikzogg** [comment]
@mitchellh any news on bugfix release?

**Pull request merged**
