### PR TITLE
Fixed Admin Verification for HyperV

### PR DESCRIPTION
**Pull request by johnrizzo1**
Fixed admin test to verify that you are running in an elevated shell, not that you are in the administrators group since that is not required.

### CODE REVIEW

**Comment by DrowningElysium** [comment]
I can confirm that this fixes the admin issues I have when trying to create smb shares

**Comment by mwrock** [comment]
This does indeed fix the issue where the hyperv provider errors stating that the user lacks admin rights when they in fact do. It currently just checks if the user is a system account and that would be very unlikely unless vagrant is running as a service.

I would remove the second commit from this PR. Its completely unrelated and IMO unnecessary since the `bridge` setting should accomplish this.

**Comment by invisibleaxm** [comment]
fwiw, I stumbled into this issue, manually applied the fix and i can also confirmed that it worked.

**Comment by wickedviking** [comment]
Regarding the VMSwitch handling, unless this could be updated to handle mutli-homed scenarios, it would better to leave it as is or update the current network processes to handle mutliple adapters/switches.

User case, setting up a Router VM to bridge two networks (local host private and lab for example) to create an isolated environment that "borrows" internet access from another network.

**Comment by mwrock** [comment]
It should at least be implemented to not break current Vagrantfiles that use the `bridge` to specify a switch. For clarity I think having a separate PR is for the best.

**Comment by chrisroberts** [comment]
Extracted the admin check to isolate change in #8548. Thank you for the PR!

**Comment by johnrizzo1** [comment]
Thank you.  I didn't intend for both to be a part of the pull request.

Regards,

John

**Pull request closed without merging**
