### PR TITLE
New command: vagrant box remove-old-versions with tests

### PR DESCRIPTION
**Pull request by bbrala**
Added a command `vagrant box remove-old-versions` to remove all but the newest version of a box in vagrant. It builds a list of  boxes that are installed and finds the newest versions. It then removes every box that had a newer version installed.

```
Usage: vagrant box remove-old-versions [options]

Options:

    -p, --provider PROVIDER          The specific provider type for the boxes to destroy.
    -n, --dry-run                    Only print the boxes that would be removed.
        --name NAME                  The specific box name to destroy.
    -f, --force                      Destroy without confirmation even when box is in use.
    -h, --help                       Print this help

```

Fixes GH-5633

### CODE REVIEW

**Comment by bbrala** [comment]
I extracted the code to a plugin also so the feature can be used before it is merged. See: https://github.com/swisnl/vagrant-remove-old-box-versions

**Comment by kylegibson** [comment]
:+1: I suspect they will want some test cases with this code

**Comment by bbrala** [comment]
Yeah probably, might do that soonish, but was getting a bit late yesterday evening. :)

**Comment by bbrala** [comment]
Added tests for all options except --force. And i added the options --dry-run and --name which were contributed to the plugin. Think everything should be ready for a merge (issue #4412)

**Comment by sethvargo** [comment]
Hi @bbrala 

I haven't forgotten about this issue, I've just been thinking. I'm not a huge fan on introducing a new command, and I think it might make more sense to have a `--prune` option on the existing `vagrant box remove` command. What do you think?

**Comment by bbrala** [comment]
Hi Seth, glad to hear it had not been forgotten.

I understand the reluctance of introducing a new command, i agree you should always be weary of putting in more and commands. I started coding this searching for the command to extend to add this functionality. But I really felt the code for removing old boxes globally was out of place in all the other commands.

I thought about putting it in the `vagrant box remove`, but that piece of code was very much aimed at handling single boxes. It felt weird to fit a option in there that would go through all your boxes, when the remove command is really made to remove one single, specific box. 

If you look at the use of language, it might fit somewhere in `vagrant box outdated`, but this is also really aimed at a single box and has a completely different goal.

I really think mixing single box command with something more global like this is a bad idea and will confuse the end user. 

If I read your proposal with perhaps a `vagrant box --prune`, i feel one would read that as pruning old versions for that given box, which could be useful. But I do feel the worth of this piece of code is really just cleaning up everything in one command, no one likes a full SSD :smile: So maybe a `—prune-all` or `--prune-global` would work. I’m not entirely sure.

I do like the feel of the word prune though. Perhaps "vagrant box prune" might be better. remove-old-versions feels clunky.

If you don't agree on the weirdness of putting it inside the remove command, that is of course fine, and I wouldn’t mind. I think my opinion is mostly a feeling of inconsistency in the back of my head.

**Comment by bbrala** [comment]
@sethvargo Think you can find the time to check my reply? I can refactor if you really want, but i do need a decision before i can do that.

**Comment by sethvargo** [comment]
Hi @bbrala 

I'm going through issues over the next few days. I'm not sure I'll get to it though.

**Comment by bbrala** [comment]
Cheers @sethvargo, i do understand the volume of issues is quite large :)

**Comment by chrisroberts** [comment]
@bbrala Hi! Reading through the history in this issue my initial reaction was a `--prune` option on the `box remove` command would be a good location for this. However, I am in agreement with the argument that `box remove` is specifically aimed at a single box, and this option would likely make the usage a bit confusing. So, I'm :+1: on the new command, but would like to see it named as `prune` (and it seems like you agree with that based on previous comment). Could you update the command name on this PR? Thanks!

**Comment by bbrala** [comment]
Cool, just to be sure, would the full command be ``vagrant prune``? Will make the time to refactor as soon as possible.

**Comment by chrisroberts** [comment]
@bbrala it would be: `vagrant box prune`

**Comment by bbrala** [comment]
Ok cool, will rebase and update.

**Comment by bbrala** [comment]
@chrisroberts i've refactored the name to prune and rebased onto master. I also added the command to the documentation. :)

**Comment by bbrala** [comment]
Hmm, looks like github is a bit confused because of the rebase. When icheck in my IDE i only see commits on my branch... weird.

**Comment by chrisroberts** [comment]
Looks like the rebase got hosed. If you can get a clean one to push, that would be great, but it's not a huge deal. I can cherrypick items out into a new PR to stage easy enough :smiley:

**Comment by bbrala** [comment]
Hmm, i'll make a  clean one and reference this pr and the issue.

**Comment by bbrala** [comment]
@chrisroberts i've openend a new pull request #7978 which is just the changes applied to master.

**Comment by chrisroberts** [comment]
Awesome, thanks! I'll close up this in favor of the new PR. Cheers!

**Pull request closed without merging**
