### PR TITLE
Fixes 7073 specification.rb undefined method group by for nilclass

### PR DESCRIPTION
**Pull request by kamigerami**
Adding PR for #7073 - As discussed in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818237 and suggested by @babilen ... 

 my bundle exec rake tests are failing locally however I am adding this as a PR to have the Travis CI tests run to make sure whether everything is fine or not. Feel free to close it or merge it depending on the output of the tests.

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @kamigerami 

Could you please rebase with master?

**Comment by kamigerami** [comment]
Hi @sethvargo. For sure! :sunglasses: :+1:

**Comment by terceiro** [comment]
you should probably credit the original author of the solution as the author of the commit ...

**Comment by kamigerami** [comment]
Absolutely @terceiro ! Crediting Christian Hofstaedtler  as the author of this solution as mentioned in the first comment made in this PR (see url link from original discussion in bugs.debian.org)

**Comment by terceiro** [comment]
I mean the commit itself should have him as the author ...

**Comment by kamigerami** [comment]
@sethvargo @terceiro @zeha updated with original author as the author of the commit.

Thank you all!

**Comment by jwmatthews** [comment]
@kamigerami this PR doesn't look right, seems like you only need 1 commit, but you have ~24 in it.   Perhaps you need to rebase against master, or re-open this PR with the single commit you intended.  

Looking forward to seeing this merged in, as I'm seeing similar issues with vagrant in Fedora 24 alpha that this 1line fix resolved.

**Comment by kamigerami** [comment]
@jwmatthews thnx for pointing that out! Should be good now!

**Comment by dustymabe** [comment]
I'll second that this patch enabled things to work on Fedora 24 alpha.

**Comment by jwmatthews** [comment]
@kamigerami looks good, hope this gets merged in.

**Comment by haisum** [comment]
How do I fix it in my Ubuntu 16.04 right now temporarily, instead of waiting for this to get merged and new package update?

**Comment by haisum** [comment]
I found it, posting for other's reference. Said file is located at `/usr/lib/ruby/vendor_ruby/vagrant/bundler.rb` replace line 275 with `Gem::Specification.reset` it will fix the issue.

**Comment by praveenkumar** [comment]
I tested this patch with fedora24 alpha and it did work, hope this gets merged in now.

**Comment by developerinlondon** [comment]
when is this getting released? The current version of Vagrant does not work with Ubuntu 16.04 when we try to install vagrant plugins (eg vagrant lxc, vagrant hostmanager etc). This would be very useful as we are currently having to hack vagrant to get this to work.

**Comment by sethvargo** [comment]
Merged in ba77d4b

**Comment by kenorb** [comment]
Manual quick-fix:

    sudo sed -i'' "s/Specification.all = nil/Specification.reset/" /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb

**Comment by berkes** [comment]
Was this ever pushed into the Ubuntu release pipeline? It's almost two years later and Ubuntu 16.04 still has this issue. If not: why not?

**Comment by zeha** [comment]
Apparently not. Apparently no bug has been opened in Ubuntu about this, and apparently nobody supplied Ubuntu with an updated package.

**Comment by berkes** [comment]
So, how do we get it there? AFAIK you don't need to open a bug-report or issue with Ubuntu, but with the one owning and providing the package. Which, AFAIK is hashicorp not?

**Comment by terceiro** [comment]
Hi, I maintain vagrant in Debian. During the Ubuntu development, most packages in Ubuntu are just copied from Debian, and vagrant is one of them. What happened here is that Ubuntu copied the last version from Debian that still had this bug, then went into freeze (when Ubuntu no longer copies packages automatically from Debian, in order to stabilize its repository and prepare for release).

So, if you are an Ubuntu user that need this fix, you need to explicitly ask the Ubuntu people for a fixed package in Ubuntu 16.04.

**Comment by zsmuller** [comment]
The problem has been reported to Ubuntu as well (still in 2016). It's even linked to the Debian ticket!
https://bugs.launchpad.net/ubuntu/+source/vagrant/+bug/1559420

There're several comments in this bug ticket -after the bug has been fixed in Debian- complaining about the delay of an Ubuntu fix. Apparently nobody from Ubuntu/Canonical is assigned to the issue, they don't care or don't know about the problem or the upstream fix.

**Pull request closed without merging**
