### PR TITLE
Create vagrant_key

### PR DESCRIPTION
**Pull request by milindc**
The old file seems not to be working so added new file

### CODE REVIEW

**Comment by briancain** [comment]
Hi @milindc - can you provide any more details as to what is not working? A vagrant log, vagrantfile, host/guest system, etc? When you open a new issue on Vagrant, it should give you a template to fill out with information to help you debug what's going on. Thanks!

**Comment by milindc** [comment]
Hello,

I am trying to create a vagrant box for that I created a VM there I need to
add a user so that when I do vagrant up it tries to use private key but
it's not dining it.

**Comment by briancain** [comment]
@milindc - My guess is you have created a Vagrant box with the incorrect insecure private key. Please refer to the documentation on Vagrant for using the right keys when setting up a base box. I'm going to go ahead and close this.

- [Creating a Base Box (for Vagrant)](https://www.vagrantup.com/docs/boxes/base.html#quot-vagrant-quot-user)
- [Default insecure keys for base box](https://github.com/mitchellh/vagrant/tree/master/keys)

Thank you!

**Comment by milindc** [comment]
Thanks for your reply!

I used these only its not working for me can you please give me the
instructions to create a vagrant box.

I have followed the following instructions

1. Create vm using Vitual Box
2. Set the default user vagrant
3. install required set of software & tools
4. then install essentials on it and then create a package.box file.
5. added the box and try vagrant up

Please let me what is the step that I missed.

**Pull request closed without merging**
