### PR TITLE
Non developer readme contribution

### PR DESCRIPTION
**Pull request by snagy22000**
Dear Mitchell,
I have written a clear, easy-to-comprehend introduction for Vagrant. I believe this introduction, free of complex technical terms, will swiftly and thoroughly inform anyone about the use-cases, merit, and advantages, including the celebrated features, of Vagrant. Seasoned developers, new programmers, and even nontechnical visitors will benefit from the clear language, exposing Vagrant to a broader range of users.
I appreciate your feedback. 
Regards Sebastian

### CODE REVIEW

**Comment by snagy22000** [comment]
added non-technical description for the README.md

**Comment by sethvargo** [comment]
Hi @snagy22000 

Thank you for submitting a Pull Request. We very heavily document the "why vagrant" section on the vagrant website here: https://www.vagrantup.com/docs/why-vagrant/.

Since the README is rendered on GitHub, it is primarily aimed at Vagrant developers and the "why" is therefore omitted. Does that make sense?

**Comment by snagy22000** [comment]
Hi @sethvargo 

Hardly anyone understands much of the impenetrable language found on GitHub READMEs; many readers have no idea what precisely a technology does and when to use it, even after reading the entire README. The reason why i was thinking it will help is, that some people are just looking around the Repos and they can see immediately what was reason behind this product.  In the end, if they go to the specific website,they can see the reason for the product. I thought it will be also catch the attention of visitors.

**Comment by sethvargo** [comment]
Hi @snagy22000 

The first thing we do in the README is link to the website. Thank you for the contribution, but I do not think this is necessary.

**Pull request closed without merging**
