### PR TITLE
Hyper-V set mac address

### PR DESCRIPTION
**Pull request by tomfanning**
Implements the ability for the Hyper-V provider to set VMs' mac address from the vagrant file. Same implementation as the set VLAN feature.

### CODE REVIEW

**Comment by kikitux** [comment]
@phinze @sethvargo looks good

**Comment by tomfanning** [comment]
*bump* anyone able to merge this please?

**Comment by phinze** [comment]
The code LGTM - @mwrock I hear you have domain knowledge and can double check the Hyper-V layer stuff here. Mind giving this a review?

**Comment by mwrock** [comment]
cool. will look today.

**Comment by mwrock** [comment]
Worked great for me testing with a win2012r2 vm on win 10 hyperv. :+1:

**Comment by sethvargo** [comment]
Thanks!

**Pull request merged**
