### PR TITLE
ansible_local: use double quoting for 'extra-vars', 'limit' and 'start-at-task' options

### PR DESCRIPTION
**Pull request by gildegoma**
### Overview

When the `extra_vars` option is a hash, the `ansible_local` provisioner must quote the generated JSON parameter. 
I also propose here that the two other quoted parameters (`limit` and `start_at_task`) also rely on double quotes (for output consistency and content flexibility).

### References

- Fixes GH-6726
- Replaces GH-6820

### CODE REVIEW

**Comment by gildegoma** [comment]
Call for reviewers: @kamazee @elsom25 @fdemmer @bertramn @warrenseine

(sorry for the massive ping broadcast, but I'm not confident with all these backslashes, and I'm afraid to have missed one of your possible use cases ;-)

**Comment by kamazee** [comment]
:+1: 
worked for me

**Comment by fdemmer** [comment]
sorry for delay, works for me! :+1:

**Comment by gildegoma** [comment]
@kamazee @fdemmer thank you very much for taking time to test this :smiley: 

Before merging, I'd like to fix the issue with the `raw_arguments` option, which values (e.g. an `--extra-vars` or `limit`) shouldn't be modified by this "quoting stuff". I'll try to do this within the next days...

**Comment by gildegoma** [comment]
Okay, with ab036dd, any `--extra-vars` parameter set via the `raw_arguments` provisioner option (a possible [typical workaround](https://github.com/mitchellh/vagrant/issues/6726#issuecomment-208836260) to this bug #6726) won't be broken with the next Vagrant release.

I'm not 100% happy with this implementation (because of the code duplications around the handling of the `raw_arguments`), but these are well covered and provides a better behaviour. I'm merging now, but please let me know if you see how we could improve it :)

**Pull request merged**
