### PR TITLE
Add support for Solus Linux

### PR DESCRIPTION
**Pull request by mattandersen**
Provide NFS service and share support for Solus Linux. Based on the
Arch and Fedora hosts.

See issue #8907.

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Not that this is really anything to do with me, but I did see this on the interwebs. Shouldn't you be detecting the Linux distribution based on the `os-release` file, and not tertiary assets like `/etc/solus-release` ?

Ideally any distro detection should first look for:

```
    /etc/os-release
    /usr/lib/os-release
```

(most of the world is stuck to using /etc/ for now because tools haven't taken the cascading priority into account)

The `ID` field in os-release is what matters most:

```ini
ID="solus"
```

This is the more robust and standard solution nowadays

**Comment by mattandersen** [comment]
I was just working from the current pattern, but you're quite right. If there is something defined by freedesktop.org that we can rely on, we should. I've updated to reflect that. I am not a Ruby programmer by trade, so I hope it is satisfactory.

**Comment by chrisroberts** [comment]
@mattandersen Hi! Thank you taking the time to create this PR. I was waiting for #8938 to land before reviewing your PR so I could make update recommendations based on the new updates. However, it looks like the updates within the linux guest nfs capability cover the need this PR is fulfilling for solus. As such, it doesn't really make sense to create explicit guest support for solus at this time. However, if there is a need for customized guest capabilities for solus in the future please don't hesitate. Your original PR and updates were great, and I'm sorry that it ended up getting covered by code not yet merged. Thanks again.

Cheers!

**Comment by mattandersen** [comment]
No worries, that was the correct solution all along but I figured something like that was bit much for me to tackle at this point. 👍

**Pull request closed without merging**
