### PR TITLE
Unlink few Gem temp files from /tmp

### PR DESCRIPTION
**Pull request by valchonedelchev**

### CODE REVIEW

**Comment by sethvargo** [comment]
Seems related to https://github.com/mitchellh/vagrant/pull/4876. What do you think @valchonedelchev?

**Comment by valchonedelchev** [comment]
@sethvargo  I think so. Feel free to ignore my pull request if you like.

**Comment by obfusk** [comment]
@sethvargo, @mitchellh: doesn't this reintroduce #4869?

**Comment by brandt** [comment]
@sethvargo @mitchellh just tested - this does indeed cause a regression of #4869

**Comment by mitchellh** [comment]
Let's look at solving the issue another way since this causes a regression. Thanks for the attempt!

**Pull request closed without merging**
