### PR TITLE
update cmd format

### PR DESCRIPTION
**Pull request by tKammy**
Add parameters to below commands' usage.

destroy, halt, package, port, provision, reload, resume, ssh, ssh-config,
status, suspend, up

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @tKammy 

Thank you for opening an issue. We generally do not document the full CLI signature in the docs, since it's available when you run `vagrant command -h`. Is there an issue you are experiencing?

**Comment by tKammy** [comment]
I understood.

>  Is there an issue you are experiencing?
I didn't know that we can use 'id' for these CLI via both `vagrant command -h` and the docs.
So, is it OK to fix 'vagrant command -h' like following?

`Usage: vagrant destroy [options] [name|id]`

**Comment by sethvargo** [comment]
Hi @tKammy 

When you say "id", do you mean the machine-id from the output of global-status?

**Comment by tKammy** [comment]
Yes, I mean the machine-id.

**Pull request closed without merging**
