### PR TITLE
Fix for #6761 (fixes incomplete #6598)

### PR DESCRIPTION
**Pull request by PeterMosmans**
See the discussions in both threads, this pull request fixes the incomplete fix of #6598 (which has its own issue, #6761 )

### CODE REVIEW

**Comment by Head** [comment]
V 1.8.1 still has this bug, see #6598 - PeterMosmans' fix is works fine for me. Please update!

**Comment by pdelre** [comment]
+1

**Comment by Stanzilla** [comment]
@sethvargo can we get this in now, please?

**Comment by chrisroberts** [comment]
Confirming this fixes issue on Windows host. Using Vagrantfile:

```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-16.04'
  config.vm.synced_folder 'C:\\', '/c'
end
```

Current v1.8.5:

```
C:\Users\spox\test> vagrant up
There was an error while executing `VBoxManage`, a CLI used by Vagrant for controlling VirtualBox. The command and stderr is shown below.

Command: ["sharedfolder", "add", "4ae98dfb-3681-42cc-b887-89511b1ae4bf", "--name", "c", "--hostpath", "C:\\"]

Stderr: VBoxManage.exe: error: Shared folder path 'C:"' is not absolute VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component Shared FolderWrap, interface ISharedFolder, callee IUnknown VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostpath).raw(), fWritable, fAutoMount)" at line 1020 of file VBoxManageMisc.cpp
```

and v1.8.5 with patch applied:

```
C:\Users\spox\test> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.0.26
    default: VirtualBox Version: 5.1
==> default: Mounting shared folders...
    default: /c => C:/
    default: /vagrant => C:/Users/spox/test
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

:+1:

**Pull request merged**
