### PR TITLE
Support arrays for data_bags_path

### PR DESCRIPTION
**Pull request by sethvargo**
Fixes GH-5988

### CODE REVIEW

**Comment by sethvargo** [comment]
This will not break backwards compatibility because the value has always been an array, we just called `.first` on it :smile:

**Comment by mitchellh** [comment]
Ah, hah! LGTM

**Comment by xeron** [comment]
Thank you guys! Small follow up: Chef 12 supports both `String` and `Array`.

**Comment by sethvargo** [comment]
@xeron correct, but Chef 11 does not. So we still have to write it out as a string or else we break backwards compat.

**Pull request merged**
