### PR TITLE
Fix #5673 - Use hostnamectl to set the hostname on Ubuntu Vivid 15.

### LINKED ISSUE #5673: config.vm.hostname for Ubuntu 15.04 fails
Error below. The hostname service is masked in ubuntu 15.04, the recommended way to control the hostname seems to be hostnamectl.

    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!
    
    service hostname start
    
    Stdout from the command:
    
    
    
    Stderr from the command:
    
    sudo: unable to resolve host ubuntu-1504
    stdin: is not a tty
    Failed to start hostname.service: Unit hostname.service is masked.

### PR DESCRIPTION
**Pull request by jfilip**
Resolves #5673.

### CODE REVIEW

**Comment by ovr** [comment]
Ping @sethvargo 
Can you review this? It's rly important fix

**Comment by baguasquirrel** [comment]
Hey guys, bump?

**Comment by mitchellh** [comment]
We'll be triaging and merging Vagrant issues shortly. Please hang on a bit longer. Thanks!

**Comment by ChiperSoft** [comment]
We're held up on upgrading to Ubuntu 15 because of this bug. Can this make it into 1.7.3?

**Comment by rogerhu** [comment]
+1

**Comment by ovr** [comment]
Next month will start very soon, maybe it's time to do it?)

**Comment by mitchellh** [comment]
LGTM. Thanks!

**Pull request merged**
