### PR TITLE
'by Hashicorp' added to header

### PR DESCRIPTION
**Pull request by captainill**
In the process of updating header I've added some mobile styling which includes a mobile nav and also a bit of cleanup.

### CODE REVIEW

**Comment by captainill** [comment]
to be clear this is the 'www' website update. The 'docs' are coming.

**Comment by captainill** [comment]
docs site is updated and included is pull request now.

**Comment by sethvargo** [comment]
screen shot 2015-12-21 at 11 09 41 am
screen shot 2015-12-21 at 11 10 19 am

**Comment by mitchellh** [comment]
Looks great! Thanks

**Pull request merged**
