### PR TITLE
select a Hyper-V switch based on a network_name

### PR DESCRIPTION
**Pull request by mwrock**
Currently if one has more than one Hyper-V switch, vagrant will require user intervention to select the switch to use when importing a machine. This is always slightly annoying and problematic when using applications such as Test-Kitchen that do not allow interactive setup of a vagrant box.

This PR allows a Vagrantfile to include a public or private network with a network name. If a switch exists with the same name, it is the one that will be chosen:

```
config.vm.network "public_network", bridge: 'External Virtual Switch'
```

Considering one has multiple switches and one is named after the `bridge`, that switch will be chosen. If no network name is specified, the the current behavior takes over and prompts the user.

This is a modified steal from @Taliesin's PR #3480 that was previously closed (due to too broad of scope from what I can tell).

### CODE REVIEW

**Comment by vvchik** [comment]
+1 for that, simple and works well, much better than #3480 and #3795, please merge this

**Comment by mwrock** [comment]
Yeah I'd love to see this pulled in. I sometimes have a external and internal switch enabled and without this patch, Test-Kitchen dies from the prompt. CC @sethvargo @mitchellh

**Comment by VladLazebnyy** [comment]
+1, please merge this

**Comment by strangercat** [comment]
Please merge this.

**Pull request merged**
