### PR TITLE
Allow metadata detection with any cURL protocol

### LINKED ISSUE #5413: Self-hosted versioning with .json file over scp
I know this isn't officially supported but my problem will maybe shed light on a bug in vagrant, so I ask anyway.

I followed a [recipe to make my own instance of vagrant cloud](https://github.com/hollodotme/Helpers/blob/master/Tutorials/vagrant/self-hosted-vagrant-boxes-with-versioning.md). Basically, I simply need to set the `config.vm.box_url` to point to my own server in the `Vagrantfile` and on the server's side I need to create a .json file following a certain structure.

The problem is that depending on the url scheme in the `config.vm.box_url`, the .json is recognized incorrectly as a VM itself instead of being correctly identified as a .json file containing versions.

First, this is how it is supposed to work:
The Vagrantfile points to myHost:
``` ruby
config.vm.box_url = "scp://vagrant@myHost:/vagrant/archlinux-x86_64/archlinux-x86_64.json"
```
And the following .json file is on the server:
``` json
{
    "description": "Base archlinux box",
    "name": "archlinux-x86_64",
    "versions": [
        {
            "providers": [
                {
                    "checksum": "5493156f8a09bacc01f7312abc921cdf838620ef",
                    "checksum_type": "sha1",
                    "name": "virtualbox",
                    "url": "scp://vagrant@myHost:/vagrant/archlinux-x86_64/boxes/archlinux-x86_64_0.1.0.box"
                }
            ],
            "version": "0.1.0"
        }
    ]
}
```
It, however, doesn't work. Vagrant fails to identify the .json file and thinks it's a VM box and tries to unzip it. [See debug log for more details](https://gist.github.com/ibizaman/54f4aa421e1aa2968910#file-failing-log-remote-json-file).

The thing is it works if I download the .json file locally and change the Vagrantfile to:
``` ruby
box.vm.box_url = "file://archlinux-x86_64.json"
```
There, the box is correctly being downloaded. [See debug log](https://gist.github.com/ibizaman/54f4aa421e1aa2968910#file-succeding-log-local-json-file).
So I suppose my setup correct and it seems the problem is due to the `scp://` scheme I'm trying to use.

Any advice? (if needed I can try to patch the code myself and provide a pull request, I'm just asking for a head start then)

### LINKED ISSUE #5635: response content type header must be declared if metadata.json is hosted
I've noticed when you host a metadata.json file for multiple versions of vagrant boxes, the content type header must be correctly state as JSON. if it plain text, vagrant doesn't treat it as a metadata.json file.

For example, I've hosts a gist for some versions of a centos box. If I just the raw link to this file, which is provided as plain text.
```bash
$ vagrant box add https://gist.githubusercontent.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json
A name is required when adding a box file directly. Please pass
the `--name` parameter to `vagrant box add`. See
`vagrant box add -h` for more help.
```

If I provide the `--name` option as an argument it still errors out
```bash
$ vagrant box add https://gist.githubusercontent.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json --name hkhalid/centos_7.0
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format

```
When you check the response header for the url https://gist.githubusercontent.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json it provides `content-type: text/plain`

However If I use [rawgit](https://rawgit.com/) which provides the correct `content-type: application/json;charset=utf-8` Things work perfectly

```bash
$ vagrant box add https://rawgit.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json
==> box: Loading metadata for box 'https://rawgit.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json'
==> box: Adding box 'hkhalid/centos_7.0' (v2.0.0) for provider: virtualbox
    box: Downloading: https://www.dropbox.com/s/tu0d158kbkwv1tn/centos_7.0_2.0.0.box?dl=1
==> box: Successfully added box 'hkhalid/centos_7.0' (v2.0.0) for 'virtualbox'!
```

As an improvement, I think vagrant should be able to parse the plain text version as JSON object, and error out if its broken. I know parsing can open a can worms, but being forced to use a third party service feel like jumping through an unnecessary hoop. It also puts a dependency on the availability of the third party service.

### PR DESCRIPTION
**Pull request by ibizaman**
This refactors quite a bit the detection algorithm.
Please check commit messages for more information.

No tests were added for this PR. This is not me being lazy but I don't see any to add.

- Fixes #5635
- Fixes #5413

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @ibizaman 

Thank you for the Pull Request, and I apologize for the delay in reviewing. I must admit, the diff here is very difficult to review. It is difficult to see what has changed versus what has just been refactored. Do you think you could clean this up a bit to make only the required changes? Then we can do another PR that includes style changes?

Additionally, this will not merge cleanly. Could you please rebase?

**Comment by ibizaman** [comment]
Hello @sethvargo, 
I'll try my best :) Is it okay for you that I rewrite the history completely then ?

**Comment by sethvargo** [comment]
@ibizaman that's fine :smile:

**Comment by ibizaman** [comment]
And about the tests, do you have an idea how could I test what I am changing/adding ?

**Comment by sethvargo** [comment]
Closing this due to comments on the other issues. Please see them for more information.

**Pull request closed without merging**
