### PR TITLE
Properly namespace the FileChecksum class

### LINKED ISSUE #6713: Automatic install of virtualbox provider fails with "unitialized constant Vagrant::Util::FileChecksum (NameError)"
Following the getting-started guide for Vagrant on Windows 10, but without installing VirtualBox first (since I saw it would be installed automatically), I did "vagrant init hashicorp/precise32" then "vagrant up."

The following was the output, and I could not proceed without installing VirtualBox manually.

```
==>  Provider 'virtualbox' not found. We'll automatically install it now...
     The installation process will start below. Human interaction may be
     required at some points. If you're uncomfortable with automatically
     installing this provider, you can safely Ctrl-C this process and install
     it manually.
==>  Downloading VirtualBox 5.0.10...
     This may not be the latest version of VirtualBox, but it is a version
     that is known to work well. Over time, we'll update the version that
     is installed.
     Progress: 100% (Rate: 9075k/s, Estimated time remaining: --:--:--)
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/hosts/windows/cap/provider_install_virtualbox.rb:36:in `provider_install_virtualbox': uninitialized constant Vagrant::Util::FileChecksum (NameError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/capability_host.rb:111:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/capability_host.rb:111:in `capability'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/environment.rb:405:in `install_provider'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:159:in `block in install_providers'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/set.rb:283:in `each_key'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/set.rb:283:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:141:in `install_providers'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:85:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/environment.rb:302:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant:174:in `<main>'
```

### PR DESCRIPTION
**Pull request by metropolislights**
Use Vagrant::Util::FileChecksum everywhere.

Fixes #6713.

### CODE REVIEW

**Comment by metropolislights** [comment]
Please review. :-)

I can confirm that VirtualBox installs successfully on OS X 10.11.2. Should I run the acceptance test suite locally?

**Comment by ashaythool** [comment]
@metropolislights Did you got any issue while running/ installing new VM after updating those ruby files?

**Comment by metropolislights** [comment]
Nope, no issues. Here's what happens after the first `vagrant up`:

<pre>
<b>==>  Provider 'virtualbox' not found. We'll automatically install it now...</b>
     The installation process will start below. Human interaction may be
     required at some points. If you're uncomfortable with automatically
     installing this provider, you can safely Ctrl-C this process and install
     it manually.
<b>==>  Downloading VirtualBox 5.0.10...</b>
     This may not be the latest version of VirtualBox, but it is a version
     that is known to work well. Over time, we'll update the version that
     is installed.
<b>==>  Installing VirtualBox. This will take a few minutes...</b>
     You may be asked for your administrator password during this time.
     If you're uncomfortable entering your password here, please install
     VirtualBox manually.
<b>==>  VirtualBox has successfully been installed!</b>
Bringing machine 'default' up with 'virtualbox' provider...
<b>==> default: Importing base box 'ubuntu/trusty64'...</b>
...
</pre>

I was not asked for my administrator password.

In the meantime, I tested on 64-bit Windows 8.1 Pro. There's one pop-up you need to click through, and you're set.

**Comment by sethvargo** [comment]
:+1: LGMT

**Comment by mitchellh** [comment]
Going to make the smaller change for 1.8.1 and just remove the namespacing in the caps. THankst hough!

**Pull request closed without merging**
