### PR TITLE
(#5180) Fix interface definition with multiple private interfaces

### PR DESCRIPTION
**Pull request by clinstid**

### CODE REVIEW

**Comment by clinstid** [comment]
Last commit will deal with cleaning up the interface definitions as they are generated by 1.7.2. However,  in testing I remembered that if you're in that state the network startup is going to fail anyway. Vagrant won't be able to ssh in and generate a working interfaces file, so the cleanup will never actually happen.

**Comment by clinstid** [comment]
@sethvargo or @mitchellh - any chance we can get this PR merged and in a release soon? There's another solution in PR #5325 if you prefer that one. Personally, I don't care which PR is merged, I just want to be able to upgrade past 1.7.1 :)

Thanks.

**Comment by sethvargo** [comment]
Hi @clinstid 

Whoops - I merged https://github.com/mitchellh/vagrant/pull/5325 earlier and didn't see this one linked. Sorry about that! Thank you for the PR and I am really sorry it has taken so long to review :smile:

**Comment by clinstid** [comment]
No problem @sethvargo, I'm just happy to see it fixed. :)

**Pull request closed without merging**
