### PR TITLE
Merge docs and www into a single static site

### PR DESCRIPTION
**Pull request by sethvargo**
This is a big commit, and I apologize in advance for the future git-blames all pointing to me. This commit does a few things:

1.  Merges the website/docs and website/www repo into a single website repo
    to be in line with other HashiCorp projects
2.  Updates to use middleman-hashicorp
3.  Converts less to scss to be in line with other projects
4.  Updates page styles to be in line with other projects
5.  Optimizes images
6.  Prepare for S3 + Fastly deployment with scripts, etc.
7.  Removes blog posts (they have been transferred to hashicorp.com with
    redirects in place
8.  Updated sitemap generation script for better SEO
9.  Fixed many broken links
10. Add description to all fields

### CODE REVIEW

**Comment by sethvargo** [comment]
@gildegoma FYI

**Comment by gildegoma** [comment]
@sethvargo Wow, the new doc site looks really neat :+1: Thanks for taking the git-blame risk ;)

Quickly found an issue though: back-tick-quoted expressions are wrongly rendered as `"<a href=#...><code>...</code></a>"`. 

See for instance https://www.vagrantup.com/docs/provisioning/ansible_intro.html#ANSIBLE_CONFIG

By the way, it sounds that when this will be fixed, we'll be able to refer to HTML headers (`h1`, `h2`) via hash URL (e.g. https://www.vagrantup.com/docs/provisioning/ansible_intro.html#Static_Inventory).

**Comment by sethvargo** [comment]
Hey @gildegoma 

They are rendered that way on purpose, so you should be able to link directly to a configuration option, like: https://www.vagrantup.com/docs/provisioning/chef_solo.html#data_bags_path

**Comment by gildegoma** [comment]
Mmmh, which means that this syntax block shouldn't be used for any other purpose then?

**Comment by gildegoma** [comment]
@sethvargo current behavior seems to be:

* when `something` is found in a list item, then the anchor link is rendered
* otherwise `something` is not rendered as a link

Samples:

* https://www.vagrantup.com/docs/vagrantfile/winrm_settings.html (no bullet list, no links although could makes sense)
* https://www.vagrantup.com/docs/provisioning/ansible_intro.html#ANSIBLE_CONFIG (links generated, although not wished... confusing)

Bonus Question: are h1,h2,h3 headers already supported (no anchor links are automatically generated at the moment). Hint welcome ;)

**Pull request merged**
