### PR TITLE
Use option hashes instead of keywords args

### PR DESCRIPTION
**Pull request by sethvargo**
/cc @mitchellh this makes me really :panda_face: 

TL;DR you can't use string keys in `**opts` keyword hashes...

### CODE REVIEW

**Comment by mitchellh** [comment]
Makes me a bit nervous to do this big of a change in a point release. Let's wait until 1.8.0 merge window to get this in. But I agree.

**Comment by sethvargo** [comment]
@mitchellh well, without this `vagrant package` commands are broken in 1.7 entirely :frowning:

**Comment by sethvargo** [comment]
And I don't know of a better way to fix this (that's what led to this rabbit hole). I don't know all the places where we could be passing string-keyed options, so I had to change them all. 

Basically, anywhere we invoke a method that uses `**opts`, we have to ensure the underlying has only contains symbol-based keys, but it is almost impossible to find all such occurrences :frowning:

**Comment by mitchellh** [comment]
A lot of these I know from looking are enforced symbol-only. The package is a bit different because its going into the action runner which used strings. But almost everywhere else is symbols. 

We should just target the fixes to get the package working only. Or does it require all of these? I'd be surprised.

**Comment by sethvargo** [comment]
@mitchellh okay. Merged in a tiny fix and we can target this for 1.8

**Pull request closed without merging**
