### PR TITLE
bugfix to bugfix for ssh-agent interaction

### PR DESCRIPTION
**Pull request by zmt**
- building on https://github.com/mitchellh/vagrant/pull/7360/
- actually fixes https://github.com/mitchellh/vagrant/issues/4275
- includes some test coverage for the changes

### CODE REVIEW

**Comment by zmt** [comment]
@sethvargo Here's my draft PR.

**Comment by zmt** [comment]
PR for issue GH-7397.

**Comment by justjake** [comment]
I'm happy this issue is being addressed! I came here today after sticking this patch in my local Vagrant install:

PUBLIC MY KEYS PLS

At Airbnb we use PKCS11 keys for server authentication, and the only way to use 'em with Net::SSH seems to be via the agent.

**Comment by zmt** [comment]
You have bumped this out of 3 releases now? Is there some problem landing it? We would really like it to be picked up soon.

**Comment by sethvargo** [comment]
@zmt a few reasons:

1. It touches a lot of parts (core), so it requires testing across all guests
2. It really only bumped one release (1.8.2 -> 1.8.6) - 1.8.3 never happened. 1.8.4 had a lot of bugs and 1.8.5 was to add support for virtualbox 5.1. We haven't done a full triage of Vagrant since 1.8.4, but I understand how this can be frustrating.
3. This isn't a feature that most users are requesting. I understand it's really important to you, but compare this to the number of people who chimed in on the VirtualBox 5.1 issue. We have to prioritize our efforts to have the largest impact until we can [hire more engineers](https://www.hashicorp.com/jobs.html) to help work on the project 😄

**Comment by twexler** [comment]
@sethvargo This is actually pretty important to us (Uber), as it affects every one of our 2500+ engineers. Anything we can do to assist in testing? Do you have a process for testing on all guests?

**Comment by sethvargo** [comment]
Hi @twexler 

Thank you for your reply. A few things:

1. Could you please rebase this?
2. Changing things in core requires that we test each guest-host-permutation. Specifically, this would need to be tested against all hosts and host versions, including Windows. Is that something you could help with?

**Comment by twexler** [comment]
@sethvargo 
1. @zmt should be rebasing soon.
2. I think we may have the resources available to do this, do you have any specific tests that you run for something like this? Is there any automation at all surrounding this?

**Comment by sethvargo** [comment]
Hey @twexler 

We are working on automation, but my current setup is a Vagrantfile. I don't have access to a Windows box at the moment to test out either. We will need to verify that:

1. Existing behavior is preserved
2. The new behavior works as intended

**Comment by zmt** [comment]
Already rebasing. I had a minor conflict. I am now struggling to bundle install and run tests.

**Comment by sethvargo** [comment]
Bundle should be straight forward (hopefully). Tests live in `test/**/*_test.rb`, and there are rake tasks, but those are integration tests. Integration tests can be run with vagrant-spec, but it's probably easier to just have a Vagrantfile and run it normally on each host.

**Comment by twexler** [comment]
@sethvargo Thanks a lot for your help, we'll get back to you on the tests, beers are on us anytime! ;)

**Comment by zmt** [comment]
Yes, I wrote a few tests for some of my changes. My rbenv is messed up right now, so I am resetting everything. I need to run the rspec and build a gem to test locally once I finish the rebase before I push.

I initially thought about doing more net-ssh mock testing until I realized there was 0 coverage there so I would have to start from scratch. I also didn't want to muddle this pr with tech debt test framework additions.

**Comment by zmt** [comment]
Doh! I screwed that rebase up! I will fix tomorrow.

**Comment by zmt** [comment]
Abandoning in favor of #7621

**Pull request closed without merging**
