### PR TITLE
Reload iface connection by NetworkManager

### PR DESCRIPTION
**Pull request by linyows**
Fix for #5590. This changes has created `/etc/sysconfig/network-script/ifcfg-# {interface}` to enable.

I used https://atlas.hashicorp.com/chef/boxes/centos-7.1

### CODE REVIEW

**Comment by dcbw** [comment]
NetworkManager dev here... you shouldn't ever need to restart NM just to get network configuration to apply.  If you know the interface name you can instead add a NAME="whatever" to the ifcfg file, then:

nmcli con reload
nmcli dev disconnect <iface>
nmcli con up <name from ifcfg file>

**Comment by dcbw** [comment]
Also note that the 'dev disconnect' isn't strictly necessary, since NM will automatically clean up the previous connection and start the new one when you call 'nmcli con up'.  It's important to do the 'nmcli con reload' though because (by popular request) NM 0.9.10 and later don't automatically watch /etc/sysconfig/network-scripts/ for changes.

**Comment by linyows** [comment]
@dcbw I see. Changed reload instead of restart.

**Comment by berendt** [comment]
I would prefer to change the commit message to `Restart NetworkManager on Red Hat based distributions` (at least `Redhad` should be changed to `Red Hat`) and to merge to second commit 421fab1 with the first commit c1c39be.

**Comment by udzura** [comment]
:+1: I want this patch!

**Comment by DQNEO** [comment]
:+1: :+1: :+1: 
I have the same problem and hope this fix will be shipped soon.

**Pull request merged**
