### PR TITLE
[Vagrant][HyperV] Customization

### PR DESCRIPTION
**Pull request by ramakrishnan**
New feature for vagrant-hyperv for including networking customization during pre-boot. With this feature one can customize which virtual switch the VM can take from the Vagrantfile.

Example usage
 ```ruby
config.vm.provider "hyperv" do |hv, override|
   hv.customize  ["virtual_switch", { type: "External", name: "External Switch", :adapter => "Ethernet" }]
end
 ```

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @ramakrishnan 

I just wanted to check in and see if you have any questions. Please also see my comment above.

This will no longer merge cleanly - would you mind performing a rebase please?

**Comment by mwrock** [comment]
@sethvargo  If there is no response here, you might take a look at https://github.com/mitchellh/vagrant/pull/5207 which does merge cleanly and conforms to the current docs.

**Comment by ramakrishnan** [comment]
@sethvargo @jeffmendoza can help you in this.

**Comment by jeffmendoza** [comment]
Hey @ramakrishnan @sethvargo, I don't have the resources to finish this up. Does #5207 work for everyone?

**Comment by vvchik** [comment]
Hi @jeffmendoza #5207 works well for me. I think is better to merge #5207 than this.

@sethvargo network features is highly needed for hyper-v, please look on #5207 and #5539

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. I have merged the other hyper-v customizations as well, so I think everything is covered :smile:

**Pull request closed without merging**
