### PR TITLE
translate windows path

### LINKED ISSUE #6702: `rsync` doesn't work on Vagrant 1.8.0
`rsync` doesn't work on Vagrant **1.8.0**, but it was ok on **1.7.4**.

- Microsoft Windows 10 build 10586
- Vagrant 1.8.0
- rsync 3.1.1-1 from msys2-i686-20150916.exe (32-bit)
- openssh 7.1p1-1 from msys2-i686-20150916.exe (32-bit)

From MSYS2 Shell:
```bash
    coreos-01: Rsyncing folder: /d/vagrant-lab/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/vagrant-lab/
Guest path: /vagrant

Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/msys32/tmp/ssh.740 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/<user_name>/.vagrant.d/insecure_private_key' --exclude .vagrant/ /d/vagrant-lab/ core@127.0.0.1:/vagrant

Error: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
Continuing without compression.

Warning: Permanently added '[127.0.0.1]:2222' (ED25519) to the list of known hosts.

mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```

see also #4586 #4073

### PR DESCRIPTION
**Pull request by penguincoder**
Resolves #6702 without reverting #6568 

- Fixes GH-6702
- Fixes GH-7046

### CODE REVIEW

**Comment by dhagberg** [comment]
This appears to solve the problem with vagrant-1.8.1 on Windows 7 x64 in a git-bash 2.7.2 shell with rsync.exe copied from an msys2 installation into /mingw64/bin/rsync.

**Comment by blah238** [comment]
@sethvargo Can we please get this merged? This is a dealbreaker for Windows users.

**Comment by parhs** [comment]
Does this address the issue for cygwin? For window hosts and bsd guests rsync is only viable/easy way

**Comment by matthew-hickok** [comment]
Did this solve the issue? Previously I would remove the 3 options in lines 77-79 from the helper.rb (which worked). When I upgraded to 1.8.5, I saw the changes to the helper.rb file, and it looks like it should detect the host and when it's a Windows host the 3 problematic options are removed. 

So I thought it would work, but the issue persisted. Reverting back to 1.8.4 with those lines removed fixed the issue again.

**Comment by penguincoder** [comment]
Vagrant 1.8.5 has been working great for me with rsync in Windows.

**Pull request merged**
