### PR TITLE
Puppet 4 and Puppet environments support

### PR DESCRIPTION
**Pull request by benh57**
Submitted for review. I can clean this up as desired, let me know.

Puppet 4 has been released, and it removed the 'manifestdir' parameter.

The proper way to run Puppet now is using Puppet environments.

This PR adds support for Puppet environments by adding two new options, 'environment_path' and 'environment'.  The binary path for puppet also changed, it is no longer in the default $PATH, so i added a binary_path option (similar to the Chef provisioner) and try to autodetect puppet's location.

However, with 'puppet apply' (which Vagrant uses), the environment's specified manifest is ignored. It requires a manifest to be passed in. For convenience in the Puppet provisioner i'm parsing the manifest from the environment config which normal puppet apply does not do.

You can however override your environment's manifest by using the pre existing manifests_path and manifest_file options.

You can specify:
puppet.environment_path = "../puppet/environments"
puppet.environment = "testenv"

-- If only environment and environments_path are specified, it will parse and use the manifest specified in the environment.conf file.
-- If manifests_path and manifest_file is specified along with the environment options, the manifest from the environment will be overridden by the specified manifest_file.
-- If manifests_path and manifest_file are specified without environments, the old non-environment mode will be used (which will fail on Puppet 4+)

Resolves https://github.com/mitchellh/vagrant/issues/5578 and https://github.com/mitchellh/vagrant/issues/3740

### CODE REVIEW

**Comment by chad-upton** [comment]
I tried adding this pull request to the current release version just to try and test puppet 4.0 by editing the 4 files directly (not sure if that would work but hey why not) and ended up getting an error like this:

```
==> puppet: Running provisioner: puppet...
==> puppet: Running Puppet with environment production...
==> puppet: bash: line 2: syntax error near unexpected token `('
==> puppet: bash: line 2: `cd /puppet &&  /opt/puppetlabs/bin/puppet apply -td --modulepath '/tmp/vagrant-puppet/modules-710e4dd99e6d3c7d65fa041dce67da70:/etc/puppet/modules' --hiera_config=/tmp/vagrant-puppet/hiera.yaml --detailed-exitcodes --environmentpath /tmp/vagrant-puppet/environments/ --environment production (default_manifest from puppet.conf, which defaults to ./manifests)'
```

Guessing that last part is being pulled in from somewhere?

**Comment by benh57** [comment]
Looks like that's a comment which is in the default/blank environment.conf. I'll fix the parser so it ignores comments.

**Comment by chad-upton** [comment]
Perfect thanks!

**Comment by ball-hayden** [comment]
I'm currently using this (I've copied the relevant files into lib/) and it seems to be working perfectly.

It would be nice to see it merged!

**Comment by benh57** [comment]
Thanks for merging this! What i didn't implement was website documentation for the new options, not sure if that is in github somewhere?

**Comment by chad-upton** [comment]
Awesome job thanks for doing this!

**Comment by sethvargo** [comment]
@benh57 done in 6bfee51 :smile:. If there's anything you'd like to add/change, the docs live in the `website/docs` folder of this repo.

**Pull request merged**
