### PR TITLE
Hyper V fuller network support 

### PR DESCRIPTION
**Pull request by taliesins**
Support for configuring network adapters for Hyper v by specifying the switch to use
Reconfigure network adapters based on configuration (not only at import time)
Better naming convention for duplicate machine names for Hyper v
Add support for different versions of Hyper V generation
Make detection of addressable ip addresses a little smarter
Can specify username and password for shared folder support
Add support for detecting nic mac addresses
Do not return 169.254.0.0 addresses for addressable addresses
Return ipv6 without scope id (ruby does not like it)
Remove shares when they are not used anymore

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @taliesins 

Thank you for the Pull Request. We just merged a bunch of customizations for Hyper-V into master. This means two things: 1. I think a few of these functions are now in master (yay!) and 2. This will no longer merge cleanly (:frowning:). Could you please rebase?

Also pinging @mwrock for some :eyes:

**Comment by mitchellh** [comment]
Closing due to lack of activity. Sorry!

**Comment by taliesins** [comment]
Weird I must have missed the ping ;) sorry

**Comment by mwrock** [comment]
Oh I missed the ping too. Weird. So sorry! I'd be happy to review if you sync it up with current master and mention me.

**Pull request closed without merging**
