### PR TITLE
Enable support for nested Hyper-V

### PR DESCRIPTION
**Pull request by PatrickLang**
Windows 10 1511 (build 10586) and 1607 (build 14393), along with Windows Server 2016 Technical Preview 5 all support nesting the Hyper-V role inside of a Hyper-V virtual machine. This can be enabled with a simple call to the PowerShell cmdlet `Set-VMProcessor` . This PR adds that ability

### CODE REVIEW

**Comment by StefanScherer** [comment]
Great! A smaller PR is more likely to get merged. Do you want to add the new key in the docs https://github.com/mitchellh/vagrant/blob/6c01aaf6aba425620751d9a7b21572a889380f72/website/source/docs/hyperv/configuration.html.md as well?

**Comment by PatrickLang** [comment]
@StefanScherer thanks! I didn't notice those docs were in the same repo. Updated.

**Comment by mwrock** [comment]
:+1:  I tested this with:
```
  config.vm.provider "hyperv" do |hv|
    hv.enable_virtualization_extensions = true
  end
```
And then confirmed via:
```
C:\dev\vagrantfile [master +2 ~0 -0 !]> Get-VMProcessor -VMName packer-hyperv-iso | fl


ResourcePoolName                             : Primordial
Count                                        : 1
CompatibilityForMigrationEnabled             : False
CompatibilityForOlderOperatingSystemsEnabled : False
HwThreadCountPerCore                         : 1
ExposeVirtualizationExtensions               : True
```

**Comment by PatrickLang** [comment]
Ping @mitchellh - is there anything else I need to do to have this (and other) PRs considered? I have a few more things I'd like to contribute as well related to Hyper-V

**Comment by chrisroberts** [comment]
@patricklang once I finish getting my hyperv env setup I'll be running through these

**Comment by PatrickLang** [comment]
@chrisroberts feel free to ping me if you have any questions on it. I'm part of that team although I focus mainly on Windows containers these days.

**Comment by PatrickLang** [comment]
Hmm, how did the unrelated comments end up here?

**Comment by chrisroberts** [comment]
Hi @PatrickLang! I have cherrypicked your commits out into an isolated branch and created a new PR for this enhancement here: #8325. Thank you very much for this contribution and please know that even though this PR is getting closed, your code is still getting merged. Cheers!

**Comment by PatrickLang** [comment]
Thanks! I'll track the other PR

**Pull request closed without merging**
