### PR TITLE
Support Virtualbox 5.0 (beta) by adding a driver, referencing it in the ...

### PR DESCRIPTION
**Pull request by Stanzilla**
...list of acceptable versions/drivers, and autoloading the file in the virtualbox plugin file.

### CODE REVIEW

**Comment by sethvargo** [comment]
Duplicate of https://github.com/mitchellh/vagrant/pull/5603?

**Comment by Stanzilla** [comment]
@sethvargo yes, see comments on that.

**Comment by Stanzilla** [comment]
updated

**Comment by Stanzilla** [comment]
@sethvargo is there a problem with my changes?

**Comment by methane** [comment]
FYI, VirtualBox 5.0 is released.

**Comment by lucasmichot** [comment]
Indeed @methane, Virtualbox 5 and Vagrant 1.7.2 don't play well
@sethvargo when is the new release of Vagrant planned ?

**Comment by mitchellh** [comment]
This week

**Comment by lucasmichot** [comment]
:+1:

**Comment by PitBeast** [comment]
:+1:

**Comment by JonathanLevi** [comment]
:+1:

**Comment by ovlach** [comment]
:+1:

**Comment by kevich** [comment]
:+1:

**Comment by Silentspy** [comment]
:+1:

**Comment by zarapico123** [comment]
:+1:

**Comment by Brade** [comment]
🙌

**Comment by kikitux** [comment]
Vagrant 1.7.3 has been released.

**Pull request merged**
