### PR TITLE
Fix Win 10 Enterprise Vagrant Error

### PR DESCRIPTION
**Pull request by mjaverto**
This fixes error for issue https://github.com/mitchellh/vagrant/issues/6117

### CODE REVIEW

**Comment by rbcarson** [comment]
Thanks for this, @mjaverto! I was trying to use Windows 10 with Hyper-V and hit this exact issue, and your fix solves the problem.

(And I'm using Hyper-V because [VirtualBox doesn't run on Windows 10 build 10525](https://forums.virtualbox.org/viewtopic.php?f=6&t=69652).)

**Comment by NickMRamirez** [comment]
Will this work with older version of PowerShell where the original exception type was defined? Or would it need to check for both types in some way?

**Comment by danoz-direct** [comment]
Thanks @mjaverto, this fix worked for me also.

I was seeing the error manifest itself after a `vagrant destroy`.

**Comment by rbcarson** [comment]
I hit this issue again after reinstalling Vagrant and forgetting about it. It's worth noting that it's not specific to Enterprise - it's a problem on Windows 10 in general.

**Comment by mitchellh** [comment]
Does this also work in earlier versions of Windows?

**Comment by mitchellh** [comment]
Just tested it locally and it looks good!

**Comment by KevinB-Work** [comment]
Not certain that this works universally with previous versions. Just Installed 1.8.1 on system that had been using 1.7.2 and it fails as it doesn't know about VirtualizationException. Manually changing the script to use VirtualizationOperationFailedException again fixes. Needs some way to detect which exception is valid

**Pull request merged**
