### PR TITLE
Add networking cap for Ubuntu guest

### PR DESCRIPTION
**Pull request by gMagicScott**
In issue #6653, configuring custom networking failed due to changes in `systemd` in Ubuntu 15.10. Vagrant defaulted to falling back to Debian configuration which hard coded `eth` and a digit to configure the networks.

In this pull request, the Debian configuration was copied to Ubuntu, checks to see if the the `eth` networks are available. If so, defer to the Debian setup.

Otherwise we lookup the open interfaces and configure them with the new "predictable names" (that can be oddly hard to predict).

One of the templates copied from Debian mentioned issue #2648. I'm not sure if it is something that is applicable to Ubuntu or the new naming schemes. I left it in since I'm not sure how to test the issue.

### CODE REVIEW

**Comment by gMagicScott** [comment]
Somewhat related is #6683. When I tested this, I was using the [boxcutter/ubuntu1510](https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1510), whose Packer build can be [found here](https://github.com/boxcutter/ubuntu/blob/master/ubuntu1510.json).

When I tested against the **ubuntu/wily64**, I still get the ssh timeout (Connection reset by peer) error. I looked for the script that builds the Ubuntu official box, but wasn't able to find it. I'm not sure what the difference is between the two setups as to why ssh fails on the official box.

I have an idea that may work, but I'm not sure how or where to hook into the Vagrant execution to run some VBoxManage commands between boot and the initial ssh connection.

**Comment by brbsix** [comment]
Do you think this PR would be a good opportunity to integrate #3957 (specifically checking `/etc/network/interfaces.d` on Ubuntu) or is that not really an issue? I'm not sure why, but https://github.com/mitchellh/vagrant/commit/e99253be6eb418ba02d66997c4643c50377c19e3 was never commited to master.

**Comment by gMagicScott** [comment]
Does anyone know when the feature was introduced into Debian / Ubuntu to be able to split network interfaces into files? It's not there from the beginning. 

If vagrant would split the network config into files, it would need to be conditionally around a version test, unless support for really old OSs doesn't matter.

**Comment by gabriel403** [comment]
Any news on what's happening with this? Really such in a hole atm.

**Comment by gabriel403** [comment]
@gMagicScott do you know of anyway we can use this without having to wait for the pr to be merged?

**Comment by gMagicScott** [comment]
@gabriel403 I tried putting this into a plugin but I couldn't get it to work. 

Currently I'm using my fork with the patch. There is documentation in the Readme and in the wiki of this repo on how to run the dev version of vagrant.

**Comment by gabriel403** [comment]
@gMagicScott thanks for the help, shame you couldn't get the plugin working 😀

**Pull request closed without merging**
