### PR TITLE
bump bundler to 1.12.5

### PR DESCRIPTION
**Pull request by mawatech**
fix for issue #7073

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi there,

Thank you for the PR. We have to stick to older versions of bundler for API compat reasons. #7073 will be fixed with the next release. Thanks!

**Comment by yonas** [comment]
@mawatech What are the exact steps to upgrading bundler to 1.12.5?

**Comment by yonas** [comment]
@mawatech  Sorry, didn't see your patch :P

**Comment by kenorb** [comment]
To upgrade bundler to 1.12.5, run:

    sudo gem install bundler --version ">= 1.12.5"

To quickly fix issue from #7073, run:

    sudo sed -i'' "s/Specification.all = nil/Specification.reset/" /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb

**Pull request closed without merging**
