### PR TITLE
omits empty ENV key when updating

### PR DESCRIPTION
**Pull request by daveespo**
Addresses #8126

### CODE REVIEW

**Comment by skoshy** [comment]
Making this change on Windows helped me overcome issue #7857, thanks @daveespo!

**Comment by AlissonPQ** [comment]
Thanks @daveespo . I believe this fix adds a bit of an extra protection, but I'm not sure the community will accept it, since it kind of conceals a more serious problem. I found @BackSlasher in depth explanation here http://blog.backslasher.net/running-external-ruby-code-from-vagrant.html and his solution to the problem was added to the 1.9 milestone, here #7047 .

**Comment by daveespo** [comment]
@AlissonPQ -- I don't entirely care about the nature of the fix ... I provided one solution but as long as the PR by @BackSlasher you reference also fixes the problem, that's fine. What's more frustrating is that both this PR and the one you reference have been open for a long time (6 weeks for this one, ONE YEAR for #7047) and there are a lot of frustrated Windows users out there that have to hand-patch vagrant to get their VMs launched

There's good reason to be cautious about accepting a fix, but not at the expense of leaving the app broken for months. Accepting my short-term, short-sighted fix would provide a lot of relief since it seems like #7047 is doomed to never get merged.

**Comment by AlissonPQ** [comment]
True. I haven't used vagrant in six months or so and I was quite surprised
to find it broken this time around when I downloaded 1.9.x. Funny fact is I
downloaded an older version of both vagrant and chef thinking that would do
it, but it only worked a few times and the issue started again (don't ask
me why). Maybe they are trying to track down exactly what's causing the
problem and release a definitive solution. Who knows?

Your fix is a standard way of adding extra security to calls that reference
strings, it eliminates the symptoms. They could accept it and open an issue
to track down the real problem. I agree that leaving the software broken
for windows users is very lame.

**Comment by chrisroberts** [comment]
Fixed via #8198 with test coverage. Thanks for this PR!

**Comment by daveespo** [comment]
Thank you for merging

**Pull request closed without merging**
