### PR TITLE
Add new provisioner: Ansible on the Guest VM (ansible_local)

### PR DESCRIPTION
**Pull request by gildegoma**
@sethvargo @mitchellh This is ready to be merged for Vagrant 1.8.0 release, if you agree with the  `ansible_local` naming.

The new provisioner is already quite usable, and the following improvements can come later in further Vagrant releases:

* [ ] `ansible-galaxy` integration (#2718)
* [ ] ability to auto install ansible via `pip` or from `source`.

Please note that during this iteration, I intentionally stick to the legacy unit tests for "refactoring safety" reasons, but new unit test coverage is also on the roadmap for upcoming releases.

### CODE REVIEW

**Comment by QWp6t** [comment]
`ansible-galaxy` should come with 1.8 imo. There is no way for Windows hosts to provision guest VM with Ansible without using shell provisioner or crossing their fingers with Cygwin/Babun.

This new provisioner is presumably supposed to address that, but without being able to use `ansible-galaxy`, it doesn't fully address the issue. At the very least, having the ability to do `ansible-galaxy install -r <filename>` (where `<filename>` is specified in Vagrantfile or as parameter) would be fantastic.

I don't speak Ruby otherwise I'd happily submit PR. I can give it a shot if you guys are willing to wait, though. It seems like it would be trivial given that the bulk of the legwork is already done as far as getting Ansible installed and ready to go.

**Comment by gildegoma** [comment]
Thanks @QWp6t for you comment. Ideally, you're right that resolving #2718 for Vagrant 1.8.0 would be optimal for the Ansible Galaxy users. But unfortunately I most probably won't have the time to fix it before the 1.8.0 release, which should come in the next days already.

I think that shipping the new `ansible_local` provisioner in its current state is already quite interesting, and this should not be stopped for lack of support for galaxy. We (maybe with your help) will certainly keep improving it within the next minor Vagrant releases in a fully backwards compatible way, and be sure that #2103 is on top of my "todo list" (for both `ansible` and `ansible_local`).

**Comment by gildegoma** [comment]
@sethvargo I'd really like to merge this now (I'll take care of the rebase step). Do you see any reason not to do it?

**Comment by gildegoma** [comment]
@mitchellh @sethvargo I merge this stuff now into master to be sure that this feature will be shipped in 1.8!
Please double check that you agree with the provisioner name *ansible_local* (analog to Packer's `ansible-local`, but following same naming style as other vagrant core provisioners like `chef_solo`, etc.).

**Comment by sethvargo** [comment]
LGTM!

**Comment by gildegoma** [comment]
@sethvargo thanks :beers: :relieved: 

Any public ETA for 1.8.0 release ?

**Comment by warrenseine** [comment]
🎉

**Comment by sethvargo** [comment]
End of the month

**Comment by gildegoma** [comment]
Excellent, I'm very excited for this release! It also givre me some time to try to add a few more things then 😏🌌

**Comment by gildegoma** [comment]
@sethvargo if you have time, I'd really appreciate that you look at the code style of this PR, and to the documentation english as well. I decided to merge it into master because its behaviour is pretty solid, and I wanted to be 100% to ship it into 1.8. It was also very handy to work on this base for further additions (like #2718). If you make this review, I'll report the items into a new issue, that I might address a bit later (most probably after 1.8 release for the non urgent things). If you don't have time/will to check it, please give me a NACK ;-)

**Pull request merged**
